
# colour various commands by default
if [ "$colour_support" = yes ]; then
    # enable color support of ls
    if [ -x /usr/bin/dircolors ]; then
    	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    	alias ls='ls --color=auto'
	fi

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'

	alias ip='ip --color=auto'
fi


# ls aliases
alias l='ls -CF'
alias ll='ls -l'
alias lli='ls -li'
alias lla='ls -lA'

# clear the "$?" value
alias ok=':'
alias mb=':'

# quickly clear the terminal
alias xx='clear'

# force python to version 3 by default
alias python='python3'
alias pip='pip3'

# you do not want to ask
alias eclp='rm -f ~/.eclipse_history; rlwrap eclipse'

# by the way, I use vim
alias ed='vim'
alias nano='vim'
alias emacs='vim'

# quick edit and reload of the .bashrc
alias eb='vim ~/.bashrc'
alias ebv='vim ~/.bash_variables'
alias ebl='vim ~/.bash_local'
alias eba='vim ~/.bash_aliases'
alias ebp='vim ~/.bash_prompt'
alias sb='. ~/.bashrc'

# edit or ls
function led {
	if [[ $# -ne 1 ]] || [[ "$1" = '-h' ]]; then
		echo 'usage: led <file>'
		if [[ $# -ne 1 ]]; then 
			return 1
		else 
			return 0
		fi
	fi
	file="$1"
	if [[ ! -e "$file" ]]; then
		parent_dir=$(dirname "$file")
		if [[ ! -d "$parent_dir" ]]; then
			echo 'path to file does not exist'
			return 1
		fi
		echo 'file does not exist, creating'
		ed "$file"
	elif [[ -d "$file" ]]; then
		ll "$file"
	elif [[ -f "$file" ]]; then
		ed "$file"
	else
		echo "that's a weird file you got there, mate"
		return 1
	fi
}

# mkdir and cd
function mkd {
	mkdir "$@"
	if [[ $? -ne 0 ]]; then
		return $?
	fi
	if [[ "$1" = '-p' ]]; then
		shift
	fi
	cd "$1"
}

# remove current directory and go back to parent
function rmd {
	old_workdir="$OLDPWD"
	dirname=$(basename "$PWD")
	cd ..
	rmdir "$dirname"
	res=$?
	if [[ $res -ne 0 ]]; then
		cd "$OLDPWD"
	fi
	export OLDPWD="$old_workdir"
	return $res
}

# get public ip
alias ipinfo='curl ipinfo.io/ip'

# download musics
alias music-dl='yt-dlp --extract-audio --audio-format mp3 --embed-thumbnail'

# quick compression and decompression
alias mktar='tar -czvf'
alias untar='tar -xvf'

# quick find by name (in the current directory)
alias f='find . -name'

# command to check the syslog quickly
for file in '/var/log/syslog' '/var/log/messages'
do
    if [[ -f "$file" ]]; then
        maybe_sudo=''
        if [[ ! -r "$file" ]]; then
            maybe_sudo='sudo '
        fi
        alias syslog="${maybe_sudo}tail -f ${file}"
		unset maybe_sudo
        break
    fi
done

# open a new terminal or a file explorer (native desktop only)
alias here='gnome-terminal'
alias xo='xdg-open'

# get the public IP
alias ipinfo='curl ipinfo.io/ip'

# for when the compilation takes way too much time
alias mk="make -j $(nproc)"

# for when even Ctrl+C won't end a program
alias solong='pkill -9'

# for when I try to quit the terminal like it's a vim editor
alias q='exit'
alias wq='exit'

# quick computer shutdown (disabled by default because it is dangerous on servers)
# alias dodo='shutdown +0'
