
let mapleader = ","

nmap <silent> <leader><space><space> :tab terminal<CR>

command Ecfg tabe ~/.vimrc
command Lcfg so ~/.vimrc

syntax on
set tabstop=4
set shiftwidth=4
set smartindent

set mouse-=a

