#!/bin/bash

if dpkg -s xserver-xorg | grep '^Status' | grep installed > /dev/null; then
	export MACHINE_IS_SERVER=true
else
	export MACHINE_IS_SERVER=false
fi


# set variable identifying the chroot you work in
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

colour_support=no
case "$TERM" in
    xterm-color|*-256color) colour_support=yes;;
esac

terminal_is_xterm=no
case "$TERM" in
	xterm*|rxvt*) terminal_is_xterm=yes;;
esac



# coloured GCC warnings and errors
# if [ "$colour_support" = yes ]; then
#      export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# fi

